# Generated by Django 5.1.7 on 2025-04-11 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(3000), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
