<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-05 22:16
=======
# Generated by Django 5.1.7 on 2025-04-04 13:11
>>>>>>> a04755aa115a7f4f36c4312aa6299d3b4a7aead5

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('posts', '0003_alter_reaction_reaction_type'),
=======
    dependencies = [
        ("posts", "0003_alter_reaction_reaction_type"),
>>>>>>> a04755aa115a7f4f36c4312aa6299d3b4a7aead5
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Love', 'Love'), ('Celebrate', 'Celebrate'), ('Laugh', 'Laugh'), ('Insightful', 'Insightful'), ('Support', 'Support')], max_length=10),
=======
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("Like", "Like"),
                    ("Heart", "Heart"),
                    ("Celebrate", "Celebrate"),
                    ("Laugh", "Laugh"),
                    ("Insightful", "Insightful"),
                    ("Support", "Support"),
                ],
                max_length=10,
            ),
>>>>>>> a04755aa115a7f4f36c4312aa6299d3b4a7aead5
        ),
    ]
