# Generated by Django 5.1.7 on 2025-03-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_reaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Heart', 'Heart'), ('Clap', 'Clap'), ('Laugh', 'Laugh'), ('Support', 'Support')], max_length=10),
        ),
    ]
