# Generated by Django 5.1.7 on 2025-05-07 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_mentions_post_mentions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='mentions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mentions',
        ),
    ]
