# Generated by Django 5.1.7 on 2025-03-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_dislike_post_like_delete_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
