# Generated by Django 5.1.7 on 2025-03-23 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_like_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='posts.attachment'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='posts.attachment'),
        ),
    ]
