# Generated by Django 5.1.7 on 2025-04-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_chatbot_message'),
        ('chat', '0002_alter_groupchat_name'),
    ]

    operations = [
    ]
