# Generated by Django 5.1.7 on 2025-04-04 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_remove_student_national_id_student_status_and_more'),
        ('chat', '0002_alter_groupchat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
    ]
