# Generated by Django 5.1.7 on 2025-03-21 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupchat_members_groupchat_supervisors_groupmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_admin_message',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='name',
            field=models.CharField(default='Group', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='supervisors',
            field=models.ManyToManyField(related_name='group_supervisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
