# Generated by Django 5.1.7 on 2025-04-04 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupchat_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='batch',
        ),
    ]
