# Generated by Django 5.1.7 on 2025-04-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_merge_20250405_1554'),
        ('chat', '0004_remove_groupchat_batch'),
    ]

    operations = [
    ]
