# Generated by Django 5.1.7 on 2025-03-23 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="status",
        ),
        migrations.AddField(
            model_name="student",
            name="national_id",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"is_student": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentbatch",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"is_student": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
