# Generated by Django 5.1.7 on 2025-04-07 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.department'),
        ),
        migrations.AddField(
            model_name='batch',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.program'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentbatch',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
        migrations.AddField(
            model_name='studentbatch',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.student'),
        ),
        migrations.AddField(
            model_name='track',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.program'),
        ),
        migrations.AddField(
            model_name='batch',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.track'),
        ),
        migrations.AddField(
            model_name='unverifiednationalid',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
        migrations.AddField(
            model_name='verifiednationalid',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch'),
        ),
    ]
