# Generated by Django 5.1.7 on 2025-03-25 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="students",
        ),
        migrations.RemoveField(
            model_name="track",
            name="department",
        ),
        migrations.AddField(
            model_name="batch",
            name="program",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="batches.program",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="batch",
            name="track",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="batches.track",
            ),
            preserve_default=False,
        ),
    ]
