# Generated by Django 5.1.7 on 2025-03-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("batches", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.supervisor"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="supervisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.supervisor",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="batches.department"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="batches.department"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="batches.program"
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="batches.track"
            ),
        ),
    ]
