# Generated by Django 5.1.7 on 2025-03-25 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0002_remove_batch_students_remove_track_department_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="national_id",
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Graduated", "Graduated")],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
