# Generated by Django 5.1.7 on 2025-03-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.TextField(blank=True),
        ),
    ]
