# Generated by Django 5.1.7 on 2025-04-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0003_remove_student_national_id_student_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
