<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-06 16:03
=======
# Generated by Django 5.1.7 on 2025-04-06 16:00
>>>>>>> 3939fb4f3f14ddc8f3b51fe3caaa15a0e3fd903e

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
=======
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0001_initial"),
>>>>>>> 3939fb4f3f14ddc8f3b51fe3caaa15a0e3fd903e
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_projects', to='users.profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='projects.tag'),
=======
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(
                blank=True, related_name="contributed_projects", to="users.profile"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="unique_lower_name"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="projects.tag"
            ),
>>>>>>> 3939fb4f3f14ddc8f3b51fe3caaa15a0e3fd903e
        ),
    ]
