# Generated by Django 5.1.7 on 2025-04-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
