# Generated by Django 5.1.7 on 2025-03-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_related_object_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content_type',
            new_name='related_object_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
