# Generated by Django 5.1.7 on 2025-03-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_related_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reaction_type',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('love', 'Love'), ('haha', 'Haha'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry')], max_length=10, null=True),
        ),
    ]
