# Generated by Django 5.1.7 on 2025-03-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_content_type_notification_related_object_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_object_type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('new_post', 'New Post'), ('mention', 'Mention'), ('message', 'Message'), ('chat', 'Chat'), ('group_chat', 'Group Chat'), ('follow', 'Follow'), ('batch_assignment', 'Batch Assignment'), ('batch_end', 'Batch End')], max_length=20),
        ),
    ]
