# Generated by Django 5.1.7 on 2025-05-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('new_post', 'New Post'), ('follow', 'Follow'), ('unfollow', 'Unfollow'), ('message', 'Message'), ('chat', 'Chat'), ('group_chat', 'Group Chat'), ('batch_assignment', 'Batch Assignment'), ('batch_end', 'Batch End')], max_length=20),
        ),
    ]
